"use strict";

const fs = require("node:fs");
const http = require("node:http");
const https = require("node:https");
const os = require("node:os");
const path = require("node:path");
const { URL } = require("node:url");

const {
  discoverAccioAppPath,
  discoverAccioConfig,
  discoverSessionSource,
  exists
} = require("../src/discovery");

const REPO_ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(REPO_ROOT, ".env");

function parseArgs(argv) {
  return {
    force: argv.includes("--force"),
    print: argv.includes("--print")
  };
}

function requestJson(urlString) {
  return new Promise((resolve, reject) => {
    const url = new URL(urlString);
    const client = url.protocol === "https:" ? https : http;
    const req = client.request(
      {
        hostname: url.hostname,
        port: url.port || (url.protocol === "https:" ? 443 : 80),
        path: `${url.pathname}${url.search}`,
        method: "GET"
      },
      (res) => {
        const chunks = [];

        res.on("data", (chunk) => chunks.push(chunk));
        res.on("end", () => {
          const text = Buffer.concat(chunks).toString("utf8");

          if ((res.statusCode || 0) < 200 || (res.statusCode || 0) >= 300) {
            reject(new Error(`HTTP ${res.statusCode || 0}: ${text.slice(0, 200)}`));
            return;
          }

          try {
            resolve(text ? JSON.parse(text) : {});
          } catch (error) {
            reject(error);
          }
        });
      }
    );

    req.on("error", reject);
    req.end();
  });
}

async function getCurrentAuthUserId(baseUrl) {
  try {
    const payload = await requestJson(`${baseUrl}/auth/status`);
    return payload && payload.user && payload.user.id ? String(payload.user.id) : null;
  } catch {
    return null;
  }
}

function quoteEnvValue(value) {
  const normalized = value == null ? "" : String(value);
  return `"${normalized.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function buildEnvFile(config) {
  const lines = [
    "# Generated by: npm run init-env",
    "# Safe to edit manually after generation.",
    `PORT=${quoteEnvValue(config.port)}`,
    `ACCIO_BASE_URL=${quoteEnvValue(config.baseUrl)}`,
    `ACCIO_HOME=${quoteEnvValue(config.accioHome)}`,
    `ACCIO_ACCOUNT_ID=${quoteEnvValue(config.accountId)}`,
    `ACCIO_AGENT_ID=${quoteEnvValue(config.agentId)}`,
    `ACCIO_WORKSPACE_PATH=${quoteEnvValue(config.workspacePath)}`,
    `ACCIO_LANGUAGE=${quoteEnvValue(config.language)}`,
    `ACCIO_SOURCE_CHANNEL_ID=${quoteEnvValue(config.sourceChannelId)}`,
    `ACCIO_SOURCE_CHAT_ID=${quoteEnvValue(config.sourceChatId)}`,
    `ACCIO_SOURCE_USER_ID=${quoteEnvValue(config.sourceUserId)}`,
    `ACCIO_SOURCE_CHAT_TYPE=${quoteEnvValue(config.sourceChatType)}`,
    `ACCIO_SOURCE_PLATFORM=${quoteEnvValue(config.sourcePlatform)}`,
    `ACCIO_SOURCE_TYPE=${quoteEnvValue(config.sourceType)}`,
    `ACCIO_REQUEST_TIMEOUT_MS=${quoteEnvValue(config.requestTimeoutMs)}`,
    `ACCIO_TRANSPORT=${quoteEnvValue(config.transportMode)}`,
    `ACCIO_AUTH_MODE=${quoteEnvValue(config.authMode)}`,
    `ACCIO_AUTH_STRATEGY=${quoteEnvValue(config.authStrategy)}`,
    `ACCIO_ACCOUNTS_CONFIG_PATH=${quoteEnvValue(config.accountsPath)}`,
    `ACCIO_ACCESS_TOKEN=${quoteEnvValue(config.accessToken)}`,
    `ACCIO_AUTH_ACCOUNT_ID=${quoteEnvValue(config.envAccountId)}`,
    `ACCIO_ACCESS_TOKEN_EXPIRES_AT=${quoteEnvValue(config.accessTokenExpiresAt)}`,
    `ACCIO_GATEWAY_AUTOSTART=${quoteEnvValue(config.gatewayAutostart)}`,
    `ACCIO_APP_PATH=${quoteEnvValue(config.appPath)}`,
    `ACCIO_GATEWAY_WAIT_MS=${quoteEnvValue(config.gatewayWaitMs)}`,
    `ACCIO_GATEWAY_POLL_MS=${quoteEnvValue(config.gatewayPollMs)}`,
    `ACCIO_DIRECT_LLM_BASE_URL=${quoteEnvValue(config.directLlmBaseUrl)}`,
    `ACCIO_CLIENT_ID_PREFIX=${quoteEnvValue(config.clientIdPrefix)}`,
    `ACCIO_SESSION_STORE_PATH=${quoteEnvValue(config.sessionStorePath)}`,
    `ACCIO_MAX_RETRIES=${quoteEnvValue(config.maxRetries)}`,
    `ACCIO_RETRY_BASE_MS=${quoteEnvValue(config.retryBaseMs)}`,
    `ACCIO_RETRY_MAX_DELAY_MS=${quoteEnvValue(config.retryMaxDelayMs)}`,
    `ACCIO_MODELS_SOURCE=${quoteEnvValue(config.modelsSource)}`,
    `ACCIO_MODELS_CACHE_TTL_MS=${quoteEnvValue(config.modelsCacheTtlMs)}`,
    `ACCIO_MAX_BODY_BYTES=${quoteEnvValue(config.maxBodyBytes)}`,
    `ACCIO_BODY_READ_TIMEOUT_MS=${quoteEnvValue(config.bodyReadTimeoutMs)}`,
    `ACCIO_AUTH_CACHE_TTL_MS=${quoteEnvValue(config.authCacheTtlMs)}`
  ];

  return `${lines.join("\n")}\n`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (exists(ENV_PATH) && !args.force && !args.print) {
    process.stderr.write(
      `.env already exists at ${ENV_PATH}. Re-run with --force to overwrite or --print to preview.\n`
    );
    process.exitCode = 1;
    return;
  }

  const baseUrl = process.env.ACCIO_BASE_URL || "http://127.0.0.1:4097";
  const accioHome = process.env.ACCIO_HOME || path.join(os.homedir(), ".accio");
  const currentUserId = await getCurrentAuthUserId(baseUrl);
  const discovered = discoverAccioConfig({
    accioHome,
    accountId: currentUserId || process.env.ACCIO_ACCOUNT_ID || ""
  });
  const accountDir = discovered.accountId
    ? path.join(discovered.accioHome, "accounts", discovered.accountId)
    : null;
  const sessionSource = accountDir
    ? discoverSessionSource(accountDir, discovered.agentId)
    : null;

  const finalConfig = {
    port: process.env.PORT || "8082",
    baseUrl,
    accioHome: discovered.accioHome,
    accountId: discovered.accountId || "",
    agentId:
      process.env.ACCIO_AGENT_ID ||
      discovered.agentId ||
      (sessionSource && sessionSource.agentId) ||
      "",
    workspacePath:
      process.env.ACCIO_WORKSPACE_PATH ||
      discovered.workspacePath ||
      "",
    language: process.env.ACCIO_LANGUAGE || discovered.language || "zh",
    sourceChannelId:
      process.env.ACCIO_SOURCE_CHANNEL_ID ||
      discovered.sourceChannelId ||
      (sessionSource && sessionSource.channelId) ||
      "weixin",
    sourceChatId:
      process.env.ACCIO_SOURCE_CHAT_ID ||
      discovered.sourceChatId ||
      (sessionSource && sessionSource.chatId) ||
      "",
    sourceUserId:
      process.env.ACCIO_SOURCE_USER_ID ||
      discovered.sourceUserId ||
      (sessionSource && sessionSource.chatId) ||
      "",
    sourceChatType:
      process.env.ACCIO_SOURCE_CHAT_TYPE ||
      discovered.sourceChatType ||
      (sessionSource && sessionSource.chatType) ||
      "private",
    sourcePlatform: process.env.ACCIO_SOURCE_PLATFORM || "pcApp",
    sourceType: process.env.ACCIO_SOURCE_TYPE || "im",
    requestTimeoutMs: process.env.ACCIO_REQUEST_TIMEOUT_MS || "120000",
    transportMode: process.env.ACCIO_TRANSPORT || "auto",
    authMode: process.env.ACCIO_AUTH_MODE || "auto",
    authStrategy: process.env.ACCIO_AUTH_STRATEGY || "round_robin",
    accountsPath:
      process.env.ACCIO_ACCOUNTS_CONFIG_PATH ||
      process.env.ACCIO_ACCOUNTS_PATH ||
      path.join(REPO_ROOT, "config", "accounts.json"),
    accessToken: process.env.ACCIO_ACCESS_TOKEN || "",
    envAccountId: process.env.ACCIO_AUTH_ACCOUNT_ID || "env-default",
    accessTokenExpiresAt: process.env.ACCIO_ACCESS_TOKEN_EXPIRES_AT || "",
    gatewayAutostart: process.env.ACCIO_GATEWAY_AUTOSTART || "1",
    appPath: discoverAccioAppPath(process.env.ACCIO_APP_PATH || ""),
    gatewayWaitMs: process.env.ACCIO_GATEWAY_WAIT_MS || "20000",
    gatewayPollMs: process.env.ACCIO_GATEWAY_POLL_MS || "500",
    directLlmBaseUrl:
      process.env.ACCIO_DIRECT_LLM_BASE_URL ||
      "https://phoenix-gw.alibaba.com/api/adk/llm",
    clientIdPrefix: process.env.ACCIO_CLIENT_ID_PREFIX || "anthropic-bridge",
    sessionStorePath:
      process.env.ACCIO_SESSION_STORE_PATH ||
      path.join(REPO_ROOT, ".data", "sessions.json"),
    maxRetries: process.env.ACCIO_MAX_RETRIES || "2",
    retryBaseMs: process.env.ACCIO_RETRY_BASE_MS || "250",
    retryMaxDelayMs: process.env.ACCIO_RETRY_MAX_DELAY_MS || "2500",
    modelsSource: process.env.ACCIO_MODELS_SOURCE || "static",
    modelsCacheTtlMs: process.env.ACCIO_MODELS_CACHE_TTL_MS || "30000",
    maxBodyBytes: process.env.ACCIO_MAX_BODY_BYTES || String(10 * 1024 * 1024),
    bodyReadTimeoutMs: process.env.ACCIO_BODY_READ_TIMEOUT_MS || "30000",
    authCacheTtlMs: process.env.ACCIO_AUTH_CACHE_TTL_MS || String(2 * 60 * 1000)
  };
  const content = buildEnvFile(finalConfig);

  if (args.print) {
    process.stdout.write(content);
    return;
  }

  fs.writeFileSync(ENV_PATH, content, "utf8");
  process.stdout.write(`Generated ${ENV_PATH}\n`);

  if (currentUserId && currentUserId !== finalConfig.accountId) {
    process.stdout.write(
      `Warning: current auth user is ${currentUserId}, but generated account is ${finalConfig.accountId}\n`
    );
  }
}

if (require.main === module) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
    process.exitCode = 1;
  });
}

module.exports = {
  main
};
